name: cineflix
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: 3.3.1
  country_code_picker: ^3.1.0
  country_picker: ^2.0.27
  country_pickers: ^3.0.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  hive: ^2.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  m_toast: ^0.2.4
  marquee: ^2.3.0
  marquee_list: ^1.0.0
  path_provider: ^2.1.5
  pinput: ^5.0.0
  shared_preferences: ^2.3.3
  tabler_icons: ^2.5.0+1
  video_player: ^2.9.2
  # walletconnect_flutter:
  walletconnect_dart:
  # web3modal_flutter: ^3.0.1
  web3auth_flutter:
  flutter_web3:
  reown_appkit: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator:
  build_runner:

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/temassets/